controllers/TaskController.php
<?php

namespace app\controllers;

use app\Components\FileCreator;
use app\crawl\ParseSites;
use app\crawl\Status;
use app\models\Flags;
use app\models\Regions;
use yii\base\Exception;
use yii\helpers\ArrayHelper;
use app\models\Engines;
use app\models\ParsedSites;
use app\models\SearchQuery;
use app\models\Structures;
use app\models\TargetSites;
use app\SearchEngine\SearchEngine;
use Yii;
use yii\base\UserException;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;

class TaskController extends PrototypeController {
    const EXPORT_LIMIT_ON_PAGE = 300;
    const SESSION_KEY_LIST_EXPORT = 'list_on_export';

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function beforeAction($action)
    {
        if ($action->id == 'render-tree') {

            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    /**
     * Displays homepage.
     *
     * @return string
     * @throws \Exception
     */
    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => SearchQuery::getList(),
            'pagination' => [
                'pageSize' => 2000
            ]
        ]);
        $this->clearSessionExport();

        return $this->render('index', [
            'data_provider' => $dataProvider
        ]);
    }

    /**
     * @TODO обработка результата
     * Кнопка очистить список задач
     * @param int $task_id
     * @return string
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionClear($task_id = 0) {
        $this->checkAuth();

        if ($task_id) {
            $iRes = SearchQuery::removeById($task_id);

        } else {
            $aId = SearchQuery::find()->select(['id'])->all();
            $aId = ArrayHelper::getColumn($aId, 'id') + [0];
            $sId = implode(',',$aId) ;
            $iRes = SearchQuery::deleteAll("id IN ($sId)");

            $aId = TargetSites::find()->select(['id'])->all();
            $aId = ArrayHelper::getColumn($aId, 'id') + [0];
            $sId = implode(',',$aId) ;
            $iRes = TargetSites::deleteAll("id IN ($sId)");
        }

        return $this->actionIndex();

    }

//    набросок отправки капчи
//    public function actionCheckcaptcha() {
//        $key = urlencode($_GET['key']);
//        $retpath = urlencode($_GET['retpath']);
//        $rep = urlencode($_GET['rep']);
//
//        $client = new \GuzzleHttp\Client();
//        $oRequest = $client->request("GET", "https://yandex.ru/checkcaptcha?key=$key&retpath=$retpath&rep=$rep")->withHeader('User-Agent', \Yii::$app->components['bot_user_agent']);
//        echo $oRequest->getBody()->getContents();
//
//        exit;
//    }

    /**
     * @return string|\yii\web\Response
     * @throws ForbiddenHttpException
     */
    public function actionCreateQuery() {
        $this->checkAuth();
        $this->clearSessionExport();

        $modelSF = new SearchQuery();
        $modelRG = new Regions();
        $aListEngines = Engines::getListForView();
        $aListRegions = Regions::getListForView();

        return $this->render('formTask', [
            'model_sf' => $modelSF,
            'model_rg' => $modelRG,
            'engine_list' => $aListEngines,
            'regions_list' => $aListRegions,
        ]);
    }

    /**
     * @return string|\yii\web\Response
     * @throws ForbiddenHttpException
     */
    public function actionCreateUrl() {
        $this->checkAuth();
        $this->clearSessionExport();

        $modelSF = new SearchQuery();
        $modelRG = new Regions();
        $aListEngines = Engines::getListForView();
        $aListRegions = Regions::getListForView();

        return $this->render('formTaskUrl', [
            'model_sf' => $modelSF,
            'model_rg' => $modelRG,
            'engine_list' => $aListEngines,
            'regions_list' => $aListRegions,
        ]);
    }

    /**
     * @throws ForbiddenHttpException
     * @throws \Exception
     * @throws \yii\db\Exception
     */
    public function actionParseDomainList() {
        $this->checkAuth();
        $this->clearSessionExport();

        $sDomainList = \Yii::$app->request->post('domain_list');

        if (!empty($sDomainList)) {
            $iTaskId = $this->addTask();

            //если больше одной ссылки
            if (strpos($sDomainList, ';') !== false) {
                $aDomainList = explode(';', $sDomainList);
            } else {
                $aDomainList = [$sDomainList];
            }
            TargetSites::insertDomainList($aDomainList, $iTaskId);
            return \Yii::$app->response->redirect('/', 301);
        }
        throw new \Exception("Некорректный список урлов");
    }

    /**
     * @param $engine_id
     * @return string
     * @throws \yii\base\Exception
     */
    private function getSearchEngineById($engine_id) {
        $sEngine = Engines::getEngineById($engine_id);
        $sEngineClass = 'app\\SearchEngine\\' . ucfirst($sEngine) . 'Search';

        return $sEngineClass;
    }


    /**
     * @todo понемногу провращается в нечитаемое нЕчто))
     * @param $task_id
     * @return string
     * @throws \yii\base\Exception
     */
    public function actionGetDomainList($task_id = 0) {
        $this->checkAuth();
        $this->clearSessionExport();

        $task_id = (int)$task_id;
        $iTaskId = $task_id ?: $this->addTask();

        if (!$iTaskId)
            throw new UserException('Некорректные данные при сохранении задачи');

        /** @var SearchQuery $oSearchQuery */
        $oSearchQuery = SearchQuery::getOneById($iTaskId);
        $sEngineClass = $this->getSearchEngineById($oSearchQuery->engine_id);

        /** @var SearchEngine $oSearchEngine */
        $oSearchEngine = new $sEngineClass($iTaskId);

        if (!empty($_POST['captcha']))
            $oSearchEngine->sendCaptcha($_POST);
        else
            $oSearchEngine->getContentOnQuery();

        if ($sCaptchaForm = $oSearchEngine->checkCaptcha(['iTaskId' => $iTaskId])) {
            return $this->render('captcha', [
               'sForm' => $sCaptchaForm
            ]);
        } else {
            $aDomainNativeList = $oSearchEngine->getDomainList();

            $oDataProvider = new ArrayDataProvider([
                'allModels' => $aDomainNativeList,
                'pagination' => [
                    'pageSize' => 30
                ]
            ]);

            return $this->render('domainNativeList', [
                'data_provider' => $oDataProvider,
                'task_id' => $iTaskId
            ]);
        }


    }

    /**
     * @return int
     */
    private function addTask() {
        $oSearchQuery = new SearchQuery();
        if ($oSearchQuery->load(\Yii::$app->request->post(), 'SearchQuery') && $oSearchQuery->validate()) {
            $iTaskId = $oSearchQuery->setTask(\Yii::$app->request->post());
            return $iTaskId;
        }

        return false;

    }

    /**
     * @todo Issue #3 Запретить ставить себя на парсинг и IP
     * @todo добавить валидацию и вынести её
     * @param $task_id
     * @throws \yii\db\Exception
     */
    public function actionSaveDomainList($task_id) {
        $aDomainList = \Yii::$app->request->post('selection');

        if (!empty($aDomainList)) {
            TargetSites::insertDomainList($aDomainList, $task_id);
            $oCrawlParser = new ParseSites();
            $oCrawlParser->start();
        }

        \Yii::$app->response->redirect('/', 301);
    }

    /**
     * @todo доделать вывод состояния процесса разбора домена
     * @param $task_id
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionShow($task_id = false) {
        $this->checkAuth();
        $this->clearSessionExport();

        $this->view->registerJsFile('@web/js/statusManager.js');

        $task_id = (int)$task_id;

        $aDomainList = $this->getDomainList($task_id, 3000);
        $query_text = SearchQuery::getSearchTextOnId($task_id);

        //@todo вынести в метод
        $aCountList = [];
        if ($task_id) {
            $aCountList['allPage'] = count($aDomainList);
            $aCountList['last_modified'] = $this->getLastModifiedOnDomainList($aDomainList);
        }


        $oDataProvider = new ArrayDataProvider([
            'allModels' => $aDomainList,
            'pagination' => [
                'pageSize' => 3000
            ]
        ]);

        return $this->render('showTaskDetail', [
            'countList' => $aCountList,
            'task_id' => $task_id,
            'query_text' => $query_text,
            'oDataProvider' => $oDataProvider,
        ]);
    }

    /**
     * @return string
     * @throws ForbiddenHttpException
     * @throws \yii\base\InvalidConfigException
     */
    public function actionShowStructureList() {
        $this->checkAuth();
        $this->view->registerJsFile('@web/js/structure.export.js');

        $iIdDomain = Yii::$app->getRequest()->get('id', 0);
        if (!empty($iIdDomain)) {
            $oSite = ParsedSites::findOne(['id' => $iIdDomain]);
            $aSelectedFlags = [];

            if (!is_null($oSite)) {
                $aFlag = Yii::$app->request->get('flags', []);

                if (!empty($aFlag)) {
                    //Сделаем фильтрацию выбранных
                    $aSelectedFlags = Flags::find()->select('name')->where(['in', 'name', $aFlag])->asArray()->all();
                    $aSelectedFlags = ArrayHelper::getColumn($aSelectedFlags, 'name');
                }

                //доп проверка на наличие домена в базе

views/task/captcha.php
<?php
/**
 * Created by PhpStorm.
 * User: Max
 * Date: 24.03.2018
 * Time: 18:28
 */

/**
 * @property $sForm
 */

?>

<?= $sForm ?>

views/task/domainNativeList.php
<?php
/**
 * Created by PhpStorm.
 * User: Max
 * Date: 08.03.2018
 * Time: 1:11
 */

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;

/**
 * @property $dataProvider
 */

$this->title = 'Подготовка структуры к выгрузке';

?>

<?php $form = ActiveForm::begin([
    'action' => 'save-domain-list?task_id='.$task_id
]); ?>
<?= Html::submitButton('Создать') ?>
<?= GridView::widget([
    'dataProvider' => $data_provider,
    'columns' => [
        ['class' => 'yii\grid\CheckboxColumn',
            'checkboxOptions' =>
                function ($model) {
                    if (empty($model['domain'])) {
                        return ['disabled' => true];
                    }
                    return ['value' => $model['domain']];
                }
        ],
        [
            'label' => 'resultHtml',
            'format' => 'raw',
            'value' => function($data){
                return Html::decode($data['resultHtml']);
            },
        ],
    ]

]); ?>



<?= Html::submitButton('Создать') ?>
<?php ActiveForm::end() ?>

views/task/formTask.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/**
 * @var array $engine_list список поисковиков
 * @var bool $form_send_success статус отправки формы
 * @var \app\models\SearchQuery $model_sf модель SearchQuery
 */

$this->title = 'Создать проект';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php $form = ActiveForm::begin(

        ([
            'action' => 'get-domain-list',
            'id' => 'create_task',
            'layout' => 'horizontal',
            'fieldConfig' => [
                'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
                'labelOptions' => ['class' => 'col-lg-1 control-label'],
            ],
        ])
    ); ?>
    <p>Пожалуйста, заполните следующие поля, для создания запроса на сбор структуры:</p>

    <?= $form->field($model_sf, 'search_text')->textInput(['autofocus' => true]); ?>
    <?= $form->field($model_sf, 'engine_id')->dropDownList($engine_list); ?>
    <?= $form->field($model_sf, 'region_id')->dropDownList($regions_list); ?>
    <p>Не более 30 слов для поиска</p>
    <?= $form->field($model_sf, 'search_words')->textarea(['value' => 'купить']); ?>
    <p>Рекомендуемые слова</p>
    <div style="border: 1px solid black; padding: 10px;">еще, ещё, отложить, купить, заказать, предзаказ, в корзину, <br>
    оформить, следить, попробовать, хочу, поделиться, добавить в корзину, в корзину, оплата и доставка, характеристики,
        рассказать друзьям, состав, выбрать, <br>
        тест, проверить результат, зарегестрироваться
    </div>
    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Создать', ['class' => 'btn btn-primary']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/task/formTaskDetail.php
<?php
/**
 * Created by PhpStorm.
 * User: Max
 * Date: 08.03.2018
 * Time: 1:11
 */

use yii\helpers\Html;
use yii\grid\GridView;

/**
 * @property $dataProvider
 */

?>

<?= GridView::widget([
    'dataProvider' => $oDataProvider,
    'columns' => [
//        ['class' => 'yii\grid\CheckboxColumn',
//            'checkboxOptions' =>
//                function ($model) {
//                    return ['value' => $model['domain']];
//                }
//        ],
        [
            'format' => 'html',
            'value' => function($model) {
                return Html::a('', ['task/show-structure-list', 'id' => $model['id']], ['class' => 'glyphicon glyphicon-list-alt']);
            }
        ],
        'domain',
        'status_message',
        'date_start',
        'last_modified',
        [
            'format' => 'raw',
            'value' => function($model) {

                $sStyle = 'color:grey;';
                if ($model['was_stopped']) {
                    $sStyle = 'color:black;cursor:pointer;';
                }

                $buttonPlay = Html::tag('p', '', [
                    'class' => 'glyphicon glyphicon-play js-play',
                    'title' => 'Добавить на парсинг',
                    'data-stopped' => (int)$model['was_stopped'],
                    'data-id' => $model['id'],
                    'style' => $sStyle
                ]);

                $sStyle = 'color:black;cursor:pointer;';
                if ($model['was_stopped']) {
                    $sStyle = 'color:grey;';
                }

                $buttonStop = Html::tag('p', '', [
                    'class' => 'glyphicon glyphicon-stop js-stop',
                    'title' => 'Добавить на парсинг',
                    'data-stopped' => (int)$model['was_stopped'],
                    'data-id' => $model['id'],
                    'style' => $sStyle
                ]);

                $sStyle = 'cursor:pointer';
                $buttonRepeat = Html::tag('p','', [
                    'class' => 'glyphicon glyphicon-repeat js-repeat',
                    'data-id' => $model['id'],
                    'title' => 'Начать занового',
                    'style' => $sStyle
                ]);

                $aButtons = [$buttonPlay, $buttonStop, $buttonRepeat];


                return implode('', $aButtons);
            }
        ]
    ]
]); ?>

<div id="js-dialog-repeat" title="Рестарт" style="display: none">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:12px 12px 20px 0;">x</span>Результат будет сброшен, Вы уверены что хотите перезапустить процесс?</p>
</div>

views/task/formTaskUrl.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/**
 * @var array $engine_list список поисковиков
 * @var bool $form_send_success статус отправки формы
 * @var \app\models\SearchQuery $model_sf модель SearchQuery
 */

$this->title = 'Создать проект';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php $form = ActiveForm::begin(

        ([
            'action' => '/task/parse-domain-list',
            'layout' => 'horizontal',
            'fieldConfig' => [
                'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
                'labelOptions' => ['class' => 'col-lg-1 control-label'],
            ],
        ])
    ); ?>
    <p>Пожалуйста, заполните следующие поля, для создания запроса на сбор структуры:</p>

    <?= $form->field($model_sf, 'search_text')->textInput(['autofocus' => true]); ?>
    <br>
    <p>Введите список урлов, разделенными точкой с запятой, без слеша на конце</p>
    <em>Например:</em>
    <b>http://test.ru; https://example.com</b>
    <div class="form-group field-searchquery-search_words">
        <br>
        <label class="col-lg-1 control-label" for="searchquery-search_words">Ссылки для обработки</label>
        <div class="col-lg-3">
            <?= Html::textarea('domain_list', '', ['placeholder'=>'http://example.com', 'class' => 'form-control']) ?>
        </div>
        <div class="col-lg-8"><p class="help-block help-block-error "></p></div>
    </div>
    <br>

    <p>Не более 30 слов для поиска</p>
    <?= $form->field($model_sf, 'search_words')->textarea(['value' => 'купить']); ?>
    <p>Рекомендуемые слова</p>
    <div style="border: 1px solid black; padding: 10px;">еще, ещё, отложить, купить, заказать, предзаказ, в корзину, <br>
        оформить, следить, попробовать, хочу, поделиться, добавить в корзину, в корзину, оплата и доставка, характеристики,
        рассказать друзьям, состав, выбрать, <br>
        тест, проверить результат, зарегестрироваться
    </div>
    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Создать', ['class' => 'btn btn-primary']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/task/index.php
<?php

/* @var $this yii\web\View */

use yii\widgets\ListView;

$this->title = 'Сбор структуры сайта';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Трекер запросов!</h1>
    </div>

    <div class="col-md-3">
        <a href="/task/create-query" class="btn btn-block btn-lg btn-success">Новый проект по поиску</a>
    </div>

    <div class="col-md-3">
        <a href="/task/create-url/" class="btn btn-block btn-lg btn-success">Новый проект через ссылки</a>
    </div>

    <div class="col-md-2">
        <a href="/task/show/" class="btn btn-block btn-lg btn-success">Список сайтов</a>
    </div>

    <div class="container-fluid">

        <div class="row">
            <div class="col-md-12">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>№</th>
                        <th>Запрос</th>
                        <th>Поисковик</th>
                        <th>Дата/время начала</th>
                        <th>Статус</th>
                    </tr>
                    </thead>
                        <?= ListView::widget([
                            'dataProvider' => $data_provider,
                            'options' => [
                                'tag' => 'div',
                                'class' => 'task-list',
                                'id' => 'task-list',
                            ],
                            'layout' => "{pager}\n{items}\n{summary}",
                            'itemView' => 'listTaskBody.php',
                            'summary' => 'Показано {begin}-{end} из {totalCount}',

                        ]);
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</div>

views/task/listTaskBody.php
<?php
use app\crawl\Status;
use yii\helpers\Html;

/** @var \app\models\SearchQuery $model */
?>


<tr <?php if ($model->status == Status::FINISH): ?>
        class="success"
    <?php elseif ($model->status == Status::ERROR): ?>
    class="danger"
<?php endif; ?>>
    <td><?= $model->id; ?></td>
    <td><a href="/task/show/<?= $model->id ?>"><?= Html::encode($model->search_text); ?></a></td>
    <td><?= $model->getEngineTitle(); ?></td>
    <td><?= $model->date_start; ?></td>
    <td>
        <?php if (isset(Status::$aStatusList[$model->status])): ?>
            <?= Status::$aStatusList[$model->status]; ?>
        <?php else: ?>
            <p class="alert-danger">Ошибка получения статуса</p>
        <?php endif; ?>
    </td>
</tr>

views/task/prepareSite.php
<?php
/**
 * Created by PhpStorm.
 * User: Max
 * Date: 08.03.2018
 * Time: 1:11
 */

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;

/**
 * @property $dataProvider
 * @property $aListValFromSession
 * @property $iTotalRow
 * @property $aStatuses
 */

$this->title = 'Подготовка структуры к выгрузке';

?>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">Статус</th>
            <th scope="col">Количество</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($aStatuses as $status) { ?>
            <tr>
                <td><?= $status['status'] ?></td>
                <td><?= $status['count'] ?></td>
            </tr>
        <?php } ?>
        <tr>
            <td><b>Всего</b></td>
            <td><?= $iTotalRow ?></td>
        </tr>
        </tbody>
    </table>

    <a href="export-structure?all=1&id=<?= $iStructureId; ?>">Экспортировать целиком</a> |||
    <a target="_blank" href="export-structure?id=<?=$iStructureId?>">Экспорт стркутуры</a>
    <!-- the treeData root element -->
    <ul id="treeData" data-csrf="<?= $_csrf ?>" data-id="<?= $iStructureId ?>">
        <item class="item" :model="treeData"></item>
    </ul>

    <script src="https://unpkg.com/vue"></script>
    <!-- item template -->
    <script type="text/x-template" id="item-template">
        <li class="list-group-item " v-bind:style="{background: rgbColor}">
<!--        <span class="badge">({{model.count}})</span>-->
            <input class="js_check" type="checkbox"
                   v-bind:checked="checked"
                   v-bind:value="model.id"
                   v-bind:data-url="model.url"
                   v-bind:data-level="model.level"
                   v-bind:data-unik-key="model.id"
            >

            {{model.status}}
            <span @click="toggle">
            <div class="panel panel-default">
                 <div class="panel-heading">{{ model.h1 }}</div>
                 <div class="panel-body">
                     <a target="_blank" v-bind:href="fullUrl">{{model.url}}</a>
                 </div>

                  <table class="table">
                      <thead>
                        <tr>
                            <th>Seo заголовок</th>
                            <th>Seo описание</th>
                            <th>Ключевые слова</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                            <td>{{model.seo_title}}</td>
                            <td>{{model.seo_description}}</td>
                            <td>{{model.seo_keywords}}</td>
                        </tr>
                      </tbody>
                      </table>
            </div>
            </span>
            <ul v-show="open" class="list-group" v-if="isFolder">
                <item
                        class="item list-group-item"
                        v-for="(model, index) in model.children"
                        :key="index"
                        :model="model">
                </item>
            </ul>
        </li>
    </script>

    <script>

        var tree = '<?= $tree ?>';
        tree = JSON.parse(tree);
        data = tree.data[0];


        // define the item component
        Vue.component('item', {
            template: '#item-template',
            props: {
                model: Object
            },
            data: function () {
                return {
                    download: false,
                    open: false
                }
            },
            computed: {
                isFolder: function () {
                    return true;
                    return this.model.children &&
                        this.model.children.length
                },
                rgbColor: function() {
                    let hue = 98 - this.model.level;
                    let color = 100 + this.model.level * 10;
                    return 'hsl('+ color + ', 80%,'+ hue + '%)';
                },
                checked: function() {
                    return this.model.checked;
                },
                fullUrl: function () {
                    return this.model.domain + this.model.url;
                }
            },
            methods: {
                toggle: function () {
                    if (this.isFolder) {
                        this.open = !this.open;
                        if (!this.model.download) {
                            Vue.set(this.model, 'download', true);
                            if (!this.model.children)
                                Vue.set(this.model, 'children', []);

                            let params = new URLSearchParams();
                            console.log(this.model);
                            params.append('domain', document.querySelector('#treeData').dataset.id);
                            params.append('branch', this.model.id);
                            params.append('level', this.model.level + 1);
                            params.append('page', 1);
                            params.append('flags', []);
                            params.append('_csrf', document.querySelector('#treeData').dataset.csrf);

                            fetch('/task/render-tree/', {
                                method: 'POST',
                                body: params
                            }).then((response) => {
                                if (response.ok) {
                                    return response.json();
                                }
                            }).then((json) => {
                                for (item in json.data) {
                                    this.model.children.push(json.data[item]);
                                }
                            });
                        }
                        this.download = true;
                    }
                },
            }
        });

        // boot up the treeData
        var treeData = new Vue({
            el: '#treeData',
            data: {
                treeData: data,
              },
            methods: {
                exportTree: function() {
                    console.log(this.treeData);
                }
            }
        })
    </script>




<?php //$form = ActiveForm::begin([
//    'action' => 'export-structure?id=' . $iStructureId
//]); ?>
<?//= Html::submitButton('Экспортировать выбранное') ?>
<!---->


<?//= GridView::widget([
//    'dataProvider'=>$dataProvider,
//    'columns' => [
//        ['class' => 'yii\grid\CheckboxColumn',
//            'checkboxOptions' =>
//                function ($model) {
//                    //@todo Чтение сессии во вьюхе...
//                    $aListValFromSession = Yii::$app->getSession()->get('list_on_export', []);
//                    $bChecked = in_array($model['id'], $aListValFromSession);
//
//                    return [
//                        'class' => 'js_check',
//                        'value' => $model['id'],
//                        'data-level' => $model['level'],
//                        'data-url' => $model['url'],
//                        'data-unik-key' => $model['id'],
//                        'checked' => $bChecked,
//                    ];
//                }
//        ],
//        [
//            'class' => 'yii\grid\ActionColumn',
//            'template' => '{cur_level} {low_level} {cur_branch}',
//            'header' => "Массовое управление",
//            'buttons' => [
//                'cur_level' => function ($url, $model) {
//                    return Html::tag('p', 'Текущий уровень', [
//                            'class' => 'js_cur_level btn btn-success btn-xs glyphicon glyphicon-resize-horizontal',
//                            'data-url' => $model['url'],
//                            'data-level' => $model['level'],
//                            'data-unik-key' => $model['id'],
//                        ]);
//                },
//                'low_level' => function ($url, $model) {
//                    return Html::tag('div','Дочерние', [
//                            'class' => 'js_low_level btn btn-success btn-xs glyphicon glyphicon-arrow-down',
//                            'data-url' => $model['url'],
//                            'data-level' => $model['level'],
//                            'data-unik-key' => $model['id'],
//                        ]);
//                },
//                'cur_branch' => function ($url, $model) {
//                    return Html::tag('div','Вся ветка', [
//                            'class' => 'js_cur_branch btn btn-success btn-xs glyphicon glyphicon-tree-deciduous',
//                            'data-url' => $model['url'],
//                            'data-level' => $model['level'],
//                            'data-unik-key' => $model['id'],
//                        ]);
//                },
//            ],
//        ],
//        'domain',
//        'level',
//        'status',
//        'url',
//        'alias',
//        'h1',
//        'seo_title',
//        'seo_description',
//        'seo_keywords',
//    ]
//]); ?>
<?//= Html::submitButton('Экспортировать в файл') ?>
<?php //ActiveForm::end() ?>

views/task/showTaskDetail.php
<?php
/**
 * Created by PhpStorm.
 * User: Max
 * Date: 08.03.2018
 * Time: 1:11
 */

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
/**
 * @property $dataProvider
 */

$this->title = 'Список доменов по запросу "' . $query_text . '"';

?>

<h1>Список доменов по запросу "<?= $query_text; ?>"</h1>


<?php //$form = ActiveForm::begin([
//    'action' => '../show-structure-list'
//]); ?>
<?php if (!empty($countList)): ?>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Кол-во страниц</th>
            <th scope="col">Дата последней обработки</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><?= $countList['allPage'] ?></td>
            <td><?= $countList['last_modified'] ?></td>
        </tr>
        </tbody>
    </table>
<?php endif; ?>


<style>
    .glyphicon {
        margin-top: 5px;
        margin-bottom: 10px;
        font-size: 21px;
        color: black;
    }
</style>

<?//= Html::submitButton('ПОКАЗАТЬ СТРУКТУРУ') ?>
<?php Pjax::begin(['id' => 'statuses']) ?>
<?php include 'formTaskDetail.php'; ?>
<?php Pjax::end() ?>
<?//= Html::submitButton('ПОКАЗАТЬ СТРУКТУРУ') ?>
<?php //ActiveForm::end() ?>